# Generated by Django 5.0.6 on 2024-06-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_rif', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=11)),
                ('direccion', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=40)),
                ('nacimiento', models.DateField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
