# Generated by Django 5.0.6 on 2024-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
