# Generated by Django 5.0.6 on 2024-06-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admon', '0002_c_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_admon.c_status'),
            preserve_default=False,
        ),
    ]
