# Generated by Django 5.0.6 on 2024-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admon', '0003_cliente_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefijo_ced_rif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo_r', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prefijo_telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo_t', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(max_length=200),
        ),
    ]
