# Generated by Django 5.0.6 on 2024-06-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admon', '0004_prefijo_ced_rif_prefijo_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_admon.c_status'),
        ),
    ]
