# Generated by Django 5.0.6 on 2024-06-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admon', '0005_alter_cliente_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_rif', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=11)),
                ('direccion', models.TextField(max_length=200)),
                ('instagram', models.CharField(max_length=40)),
                ('nacimiento', models.DateField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_admon.c_status')),
            ],
        ),
    ]
