# Generated by Django 5.0.6 on 2024-06-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admon', '0007_colaborador_especialidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidad',
            new_name='Servicio',
        ),
        migrations.RenameField(
            model_name='colaborador',
            old_name='especialidad',
            new_name='Servicio',
        ),
    ]
